name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: gradle/wrapper-validation-action@v1
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ matrix.java }}
          cache: 'gradle'
          distribution: 'temurin'
      - name: build
        run: ./gradlew build --stacktrace
