name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
      - name: JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          cache: 'gradle'
          distribution: 'temurin'
      - name: build
        run: ./gradlew build --stacktrace
