name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish_gradle:
    name: Publish to gradle portal
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 11
          cache: 'gradle'
          distribution: 'temurin'
      - name: build
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew publishPlugin
